[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
; Ép hệ thống sử dụng mạch nạp ST-Link V2
upload_protocol = stlink
debug_tool = stlink

; Cho phép dùng lệnh Serial.print() qua cổng USB Type-C/Micro-USB
build_flags = 
	-Os
	--specs=nano.specs

; Tải tự động thư viện Hệ điều hành FreeRTOS
lib_deps =
    stm32duino/STM32duino FreeRTOS @ ^10.3.1
    chris--a/Keypad @ ^3.1.1
    miguelbalboa/MFRC522 @ ^1.4.10
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.1
	marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
	adafruit/Adafruit GFX Library @ ^1.11.9
    
    adafruit/DHT sensor library @ ^1.4.6
	adafruit/Adafruit SH110X @ ^2.1.8